### ISSUE TITLE
Make 2.0.1 release

### ISSUE THREAD

**Issue by mvorisek** [atk4/schema#33]
Is it possible to make 2.0.1 release (to include the 29 and 31 issues)?

**Comment by DarkSide666** [comment]
2.0.1 released

**Comment by mvorisek** [comment]
@DarkSide666 

Please check the release source branch.

Compare
https://github.com/atk4/schema/blob/2.0.0/composer.json
vs
https://github.com/atk4/schema/blob/2.0.1/composer.json

The new `2.0.1` requires `"atk4/dsql": "dev-develop"` which does not seem to be right (and it can not be installed by default by composer if the standard stability is configured)

**Comment by mvorisek** [comment]
And include #34 in that release if possible.

**Comment by DarkSide666** [comment]
#34 merged in develop.
I will make new minor release, but probably will not manage to do that today.

**Comment by DarkSide666** [comment]
2.0.2 release is out now

**Comment by mvorisek** [comment]
@DarkSide666 Thanks! A small question - shouldn't this package require `atk4/data`? This package is used in the main `Migration` class, see https://github.com/atk4/schema/blob/develop/src/Migration.php#L6 If this package is required not for production any project, it can be put into dev dependencies, but is there any reasoning to not requiring libs that are actually required?
